### ISSUE TITLE
Texture Paths

### ISSUE THREAD

**Issue by t-affeldt** [Rotfuchs-von-Vulpes/what_is_this_uwu-minetest#6]
I haven't seen this cause a direct issue so far, but it is best practice to follow the usual naming conventions for textures, i.e.

- move your screenshots (like the tree.png) into a different folder so they aren't loaded in the game
- use a prefix for the other assets to prevent conflicts with other mods (e.g. left_side.png -> wit_left_side.png)

**Comment by Rotfuchs-von-Vulpes** [comment]
Done (some time ago)! Thank you!
