### ISSUE TITLE
Incorrect handling of brackets/newline characters

### ISSUE THREAD

**Issue by axcore** [Rotfuchs-von-Vulpes/what_is_this_uwu-minetest#9]
`what_is_this_uwu.destrange()` does not actually work on brackets; everything after the opening bracket is removed, but not the opening bracket itself.

Quick fix is to replace line 106 with

`                elseif reading and not between_parenthesis and char ~= "(" then`

If the description contains multiple lines, the text displayed in uwu's HUD is bigger than the HUD background, which looks weird. An easy fix is to insert this just before line 106:

`                elseif char == "\n" then
                    return temp_str`

**Comment by Rotfuchs-von-Vulpes** [comment]
fix!
